### ISSUE TITLE
Question about visualize

### ISSUE THREAD

**Issue by DeanLee-CHN** [flrngel/Self-Attentive-tensorflow#1]
Hello,in line 130 of 'train.py',you have ultilized the first row of A to visulize the weight of each word in a sentence,right?
If so,I would like to ask,which row of A is trully represent the weight of each word?Coz the shape of A is [r,n],and it means that we look up the whole sentence from r respectives.
Look forward to your reply.

**Comment by flrngel** [comment]
all of row represent weight of each word
I think you missed batch size
A has shape (batch_size, r, n)
